#+draft: true
#+title: Digital Art with NixOS
#+date: 2023-01-15
#+categories[]: Art
#+tags[]: Digital_Art Linux NixOS Art_for_Beginners



* TLDR
This article describes how I have configured my Linux workstation using NixOS to learn the basics of digital art. Including installing Krita, and managing it's config files. Configuring a Wacom drawing tablet, and managing completed projects with git.

* Krita
[[https://krita.org/en/][Krita]] is a Free and Open Source drawing program, comparable to Photoshop or ClipStudio Paint. As a total beginner the idea of not having a subscription was really appealing to me. Krita is fully featured and supports all of the major tasks I would need to do. The main issue that I ran into was managing Krita's configuration files. Krita is unsuprisingly managed via it's GUI, and these files are changed each time you change something within Krita. The problem arises with how NixOS, manages these sort of files.

I store all my configuration files in a single [[https://github.com/Iron-Shark/Technonomicon][repository]]. These files are then added to the "Nix Store", a collection of files used by the Nix package manager to build my user environment. With Krita I do this by targeting the files in my configuration repository with NixOS [[https://nixos.wiki/wiki/Home_Manager][Home-Manager]] and telling it where to write the file to.

#+begin_src nix
  home.file."kritarc" = {
    source = ./Krita/kritarc;
    target = ".config/kritarc";
  };
#+end_src

The problem is that since these files are linked to the Nix Store and not my configuration repository, any changes I make to Krita will be overwritten the next time I update or rebuild my system. I got around this by creating script that copies the most recent version of my Krita files into my configuration repository immediately prior to each system rebuild.

#+begin_src nix
home.file."vortex-upgrade.sh" = {
  target = ".config/system-scripts/vortex-upgrade.sh";
  executable = true;
  text = ''
    #!/bin/sh

    cd ~/Projects/Technonomicon/
    cp -f ~/.config/kritarc Machine-Vortex/Que/Krita/kritarc
    cd -
  '';
};
#+end_src
